### ISSUE TITLE
Tests timing out on newRule

### ISSUE THREAD

**Issue by DoriftoShoes** [StackStorm/st2e2e#12]
Currently the tests are not completing successfully.  Here is the output of a test run:

```
(virtualenv)root@webtest001:/tmp/st2e2e_master_1432762253_28534# DISPLAY=:10 python webui/test_st2web.py TestSt2web fedora-staging201 8080 testu testp
>>> Start st2web on Firefox at http://fedora-staging201:8080
      browser: Running on Firefox
      browser: Navigating to http://fedora-staging201:8080
      web page: Wait for //div[contains(@class,"login")] to be present
>>> Login as testu/testp
      browser: Navigating to http://fedora-staging201:8080
      web page: Wait for //div[contains(@class,"login")] to be present
      web page: Wait for //input[contains(@ng-model,"username")] to be present
      web element: Type value testu
      web page: Wait for //input[contains(@ng-model,"password")] to be present
      web element: Type value testp
      web page: Wait for //input[contains(@value,"Connect")] to be clickable
      web element: Click
    Wait for History to load
      web page: Wait for //div[contains(@class,"panel__toolbar-title") and contains(text(), "History")] to be present
<<< Logged-in successfully
    Switch to Actions
      web page: Wait for //a[contains(@href, "actions")] to be present
      web page: Wait for //a[contains(@href, "actions")] to be clickable
      web element: Click
    Wait for Actions to load
      web page: Wait for //div[contains(@class,"panel__toolbar-title") and contains(text(), "Actions")] to be present
>>> Run action core.local and get its status
      web page: Wait for //div[contains(@class, "view st2-actions")] to be present
    Find the column name with value core.local in the list and click on its row
      web page: Wait for //div[contains(@class, "column-name") and contains(@title, "core.local")] to be present
      web element: Get sub-element ..
      web element: Click
      web page: Wait for //div[contains(@class, "actions__details-column-time")] to be present
E>>> Close browser
>>> Start st2web on Firefox at http://fedora-staging201:8080
      browser: Running on Firefox
      browser: Navigating to http://fedora-staging201:8080
      web page: Wait for //div[contains(@class,"login")] to be present
>>> Login as testu/testp
      browser: Navigating to http://fedora-staging201:8080
      web page: Wait for //div[contains(@class,"login")] to be present
      web page: Wait for //input[contains(@ng-model,"username")] to be present
      web element: Type value testu
      web page: Wait for //input[contains(@ng-model,"password")] to be present
      web element: Type value testp
      web page: Wait for //input[contains(@value,"Connect")] to be clickable
      web element: Click
    Wait for History to load
      web page: Wait for //div[contains(@class,"panel__toolbar-title") and contains(text(), "History")] to be present
<<< Logged-in successfully
    Switch to Rules
      web page: Wait for //a[contains(@href, "rules")] to be present
      web page: Wait for //a[contains(@href, "rules")] to be clickable
      web element: Click
    Wait for Rules to load
      web page: Wait for //div[contains(@class,"panel__toolbar-title") and contains(text(), "Rules")] to be present
      web page: Wait for //div[contains(@class, "view st2-rules")] to be present
>>> Delete 0 existing rules
    Switch to Rules
      web page: Wait for //a[contains(@href, "rules")] to be present
      web page: Wait for //a[contains(@href, "rules")] to be clickable
      web element: Click
    Wait for Rules to load
      web page: Wait for //div[contains(@class,"panel__toolbar-title") and contains(text(), "Rules")] to be present
>>> Create a rule rule00746c43-600f-488e-9252-0a2649a6f38e (with trigger core.st2.webhook and action core.local)
      web page: Wait for //div[contains(@class, "view st2-rules")] to be present
      web page: Wait for //button[contains(@class,"st2-panel__toolbar-button")] to be present
      web element: Click
      web page: Wait for //div[@ng-model="newRule"]/div[@name="name"]/label/input to be present
E>>> Close browser

======================================================================
ERROR: test_run_action (__main__.TestSt2web)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "webui/test_st2web.py", line 31, in test_run_action
    action_status = self.st2web.get_actions_page().run_action(tested_action, **action_arguments)
  File "/tmp/st2e2e_master_1432762253_28534/webui/lib/st2web_actions_page.py", line 18, in run_action
    previous_timestamp = self.get_last_timestamp()
  File "/tmp/st2e2e_master_1432762253_28534/webui/lib/st2web_actions_page.py", line 50, in get_last_timestamp
    return result.get_text()
  File "/tmp/st2e2e_master_1432762253_28534/webui/lib/web/selenium_web_element.py", line 28, in get_text
    text = self.element.text
  File "/tmp/st2e2e_master_1432762253_28534/virtualenv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 61, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/tmp/st2e2e_master_1432762253_28534/virtualenv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 402, in _execute
    return self._parent.execute(command, params)
  File "/tmp/st2e2e_master_1432762253_28534/virtualenv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 175, in execute
    self.error_handler.check_response(response)
  File "/tmp/st2e2e_master_1432762253_28534/virtualenv/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
    raise exception_class(message, screen, stacktrace)
StaleElementReferenceException: Message: Element not found in the cache - perhaps the page has changed since it was looked up
Stacktrace:
    at fxdriver.cache.getElementAt (resource://fxdriver/modules/web-element-cache.js:8953)
    at Utils.getElementAt (file:///tmp/tmpTJKQgb/extensions/fxdriver@googlecode.com/components/command-processor.js:8546)
    at WebElement.getElementText (file:///tmp/tmpTJKQgb/extensions/fxdriver@googlecode.com/components/command-processor.js:11704)
    at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmpTJKQgb/extensions/fxdriver@googlecode.com/components/command-processor.js:12274)
    at fxdriver.Timer.prototype.setTimeout/<.notify (file:///tmp/tmpTJKQgb/extensions/fxdriver@googlecode.com/components/command-processor.js:603)

======================================================================
ERROR: test_web_trigger (__main__.TestSt2web)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "webui/test_st2web.py", line 50, in test_web_trigger
    self.st2web.get_rules_page().create_rule(new_rule_name, tested_trigger, tested_action, **rule_arguments)
  File "/tmp/st2e2e_master_1432762253_28534/webui/lib/st2web_rules_page.py", line 32, in create_rule
    rule_name_field = self.wait_and_get_element(rules_page, st2web_locators.RULES_NEW_RULE_NAME)
  File "/tmp/st2e2e_master_1432762253_28534/webui/lib/st2web_common.py", line 49, in wait_and_get_element
    return page.wait(wait_element)
  File "/tmp/st2e2e_master_1432762253_28534/webui/lib/web/selenium_web_page.py", line 16, in wait
    found = WebDriverWait(self.browser.get_native_driver(), WebPage.LONG_WAIT).until(condition.getObject())
  File "/tmp/st2e2e_master_1432762253_28534/virtualenv/local/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 75, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message: 
Stacktrace:
    at FirefoxDriver.prototype.findElementInternal_ (file:///tmp/tmpWrPSwU/extensions/fxdriver@googlecode.com/components/driver-component.js:10271)
    at fxdriver.Timer.prototype.setTimeout/<.notify (file:///tmp/tmpWrPSwU/extensions/fxdriver@googlecode.com/components/driver-component.js:603)

----------------------------------------------------------------------
Ran 2 tests in 223.659s

FAILED (errors=2)
```

**Comment by kirilstrax** [comment]
Fixed both tests: several selectors have changed + status of the action
